### ISSUE TITLE
HttpClient.Timeout does not work if DNS resolution is failing

### ISSUE THREAD

**Issue by karelkral** [MewsSystems/eet#10]
Happened in case of internet connection failure. When DNS resolution is not functional, HttpClient.Timeout is set to 2 s but effective time spent in EetClient is 15 sec. That means that Timeout does not work well in this case.

I think that this documented feature in HttpClient and we can do nothing with it: A Domain Name System (DNS) query may take up to 15 seconds to return or time out. If your request contains a host name that requires resolution and you set Timeout to a value less than 15 seconds, it may take 15 seconds or more before a WebException is thrown to indicate a timeout on your request.

**Comment by jirihelmich** [comment]
Thank you for pointing this out. Related work: http://stackoverflow.com/questions/26962615/how-can-i-specify-a-connection-only-timeout-when-executing-web-requests

**Comment by karelkral** [comment]
I spent many many time trying to resolve this issue with HttpWebRequest. Not trivial issue. 

So I tried to use  HttpClient in your way and I have found that this async solution has the same issue as my sync solution. Very sad. 

I think that this can be solved with this http://stackoverflow.com/a/22078975/245460
But I see that there is no request cancellation and disposal in case of timeout.

**Comment by karelkral** [comment]
http://stackoverflow.com/questions/26962615/how-can-i-specify-a-connection-only-timeout-when-executing-web-requests does not work. The point is that request.GetRequestStream() does not respect timeout in this case (DNS failing).

**Comment by jirihelmich** [comment]
Pavel Šorejs provided us with the following: https://support.microsoft.com/en-us/kb/2834226

**Comment by karelkral** [comment]
Thanks, Pavel. But this is system-wide settings and not every customer give me an access to change this settings. So I keep trying to resolve thsi issue in .NET.

**Comment by jirihelmich** [comment]
Sure, it's just that it seems that there is no .NET override for this behavior, so it's good to know, what the behavior is.  If there is a .NET solution for this, I prefer it as well. In other words, I do not consider this to be a solution. E.g. I cannot change such settings on Azure.

**Comment by todvora** [comment]
I am coming from Java world, but the problem is the very same. I have virtually no control over DNS lookup timeout from Java. It's totally up to the underlying OS. 

The only meaningful solution I found so far:

- Start the DNS lookup in a separate thread, which I can monitor and set timeout, before the connection to an endpoint takes place.
- If the DNS lookup succeeds, the results are cached internally (java.net.InetAddress class) and re-used during actual connection to the server.
- If the timeout occurs on the thread, exception is thrown and the communication terminates immediately.

This allows me to terminate the DNS lookup much sooner before the OS timeout occurs. 

Some implementation links:
- [DNS resolver with timeout](https://github.com/todvora/eet-client/blob/master/src/main/java/cz/tomasdvorak/eet/client/networking/DnsResolverWithTimeout.java)
- [DNS lookup before a webservice port is created](https://github.com/todvora/eet-client/blob/0464876b1c1b8435a04b2c82d319161e8950e738/src/main/java/cz/tomasdvorak/eet/client/security/SecureEETCommunication.java#L77)

**Comment by jirihelmich** [comment]
Sounds like we cannot fix this. Sorry.
