### ISSUE TITLE
Issue with date time formatting  of sale date and send date

### ISSUE THREAD

**Issue by mmaganti** [MewsSystems/eet#26]
There is an issue with date time formatting. I am passing the Revenue.Accepted (sale date time) in Czech time zone with correct time zone info. But the values are converted back to local time (in DateTimeConverter.ToEetDateTime method). I think the API assumes the local time zone corresponds to the  Czech time zone. In my case, my application is hosted on a cloud service and runs on a server in EST time zone but the software is used by people in Czech. Hence, even though i am passing the time in correct Czech time zone, they are converted back to EST time before sending the request.

I think the API need to check if the timezone info set to the Revenue.Accepted corresponds to  Czech time zone, then it should not perform any conversion and send the values as is in the request.

**Comment by jirihelmich** [comment]
Sounds a lot like https://github.com/MewsSystems/eet/issues/23

Do you have the latest version?

**Comment by mmaganti** [comment]
I have installed from NuGet version 1.1.7. Is there any latest version after this?

**Comment by mmaganti** [comment]
I came across this in #23 'As the government made it now clear that it is possible to use any timezone identifier'. Can any one provide me the link to this government clarification.

**Comment by jirihelmich** [comment]
Oh, now I understand your issue. So the time data are correct (the correct
time), but you would like to see it converted to cz timezone?

E.g.

You would expect

2017-03-28T19:39:00+01:00

But it is

2017-03-28T13:40:00-05:00

Which is the same utc time, right?

If this is the issue, I tried hard, but the issue is that XML serializer
can handle only DateTimeKind.Local. And since in a newer version of help
(not at pc now => no link) I saw that it does not expect times in +01 or
+02 only as that's how it seemed from the original docs, I stopped digging
around.

As long as the derived utc time information is correct, it can be passed
with any timezone (but a corresponding one).

**Comment by mmaganti** [comment]
Yes, you are right. I passed 2017-03-28T19:39:00+01:00 to Reveneue.Accepted which is changed to 2017-03-28T13:40:00-05:00 in the XML. Do you have the link where the government clarified to use any time zone.

**Comment by jirihelmich** [comment]
I will find it tomorrow.

On Tue, 28 Mar 2017 at 19:53, mmaganti <notifications@github.com> wrote:

Yes, you are right. I passed 2017-03-28T19:39:00+01:00 to Reveneue.Accepted
which is changed to 2017-03-28T13:40:00-05:00 in the XML. Do you have the
link where the government clarified to use any time zone.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/MewsSystems/eet/issues/26#issuecomment-289851496>, or mute
the thread

**Comment by mmaganti** [comment]
Currently, I am modifying the XML in the XmlMessageSerialized with the correct time values but the PKP will still contain the time in EST.

**Comment by jirihelmich** [comment]
![image](https://cloud.githubusercontent.com/assets/174768/24449334/41a7700a-1477-11e7-8f31-9f44b3c29f03.png)

In http://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf

You probably do not understand CZ, so let me translate for you:

```
+hh:mm, nebo –hh:mm nebo Z v případě, že hodnota je uvedena v jiné časové zóně (mimo
ČR).
```

```
+hh:mm, or –hh:mm or Z in case the value is passed in other timezone (outside of the Czech republic).
```
